[indexAndForward]
index = true
selectiveIndexing = true

[tcpout]
defaultGroup = primary_indexers
forwardedindex.filter.disable = true
indexAndForward = false
forwardedindex.0.whitelist = .*
forwardedindex.1.blacklist = _.*
forwardedindex.2.whitelist = (_audit|_internal)

[tcpout:primary_indexers]
server = <S1-SPLUNK-IP>:9997
