# ------------------------------------ CUSTOM INDEXES ------------------------------------

[gyk_test]
homePath   = $SPLUNK_DB/gyk_test/db
coldPath   = $SPLUNK_DB/gyk_test/colddb
thawedPath = $SPLUNK_DB/gyk_test/thaweddb