[custom_sysmon_linux_network]
search = index = osnix sourcetype="linux:sysmon" signature_id="3"

[custom_sysmon_linux_process]
search = index = osnix sourcetype="linux:sysmon" (signature_id IN ("1","5","9") )

[custom_sysmon_linux_filemod]
search = index = osnix sourcetype="linux:sysmon" (signature_id IN ("11","23") )

[custom_sysmon_linux_service]
search = index = osnix sourcetype="linux:sysmon" (signature_id IN ("4","16") )
