[eventtype=custom_sysmon_linux_network]
network = enabled
communicate = enabled

[eventtype=custom_sysmon_linux_process]
process = enabled
report = enabled

[eventtype=custom_sysmon_linux_filemod]
endpoint = enabled
filesystem = enabled

[eventtype=custom_sysmon_linux_service]
service = enabled
report = enabled
