[strip_syslog_prefix]
REGEX = ^\S+\s+\S+\s+\S+\s+sysmon:\s+(<Event>.*</Event>)$
FORMAT = _raw::$1
DEST_KEY = _raw

[force_sourcetype_linux_sysmon]
SOURCE_KEY = _raw
DEST_KEY = MetaData:Sourcetype
REGEX = Provider Name=\"(Linux-Sysmon)\"
FORMAT = sourcetype::linux:sysmon

[custom_sysmon_linux_eventid]
REGEX = <EventID>(\d+)</EventID>
FORMAT = EventID::$1

[custom_sysmon_linux_keywords]
REGEX = <Keywords>(0x[0-9a-fA-F]+)</Keywords>
FORMAT = Keywords::$1

[custom_sysmon_linux_computer]
REGEX = <Computer>(.*?)</Computer>
FORMAT = Computer::$1

[custom_sysmon_linux_data]
REGEX = <Data Name="(.*?)">(.*?)</Data>
FORMAT = $1::$2

[custom_sysmon_linux_filename]
SOURCE_KEY = TargetFilename
REGEX = (?<file_name>[^\\\\]+$)

[custom_sysmon_linux_eventid_lookup]
default_match = Unknown
filename = sysmon_for_linux_eventid.csv
min_matches = 1
